### ISSUE TITLE
Testing: postgraphql_test_auth_role does not exist

### ISSUE THREAD

**Issue by tim-field** [calebmer/postgraphql#127]
I'm at a bit of a lose end as to how to test this https://github.com/calebmer/postgraphql/pull/115

I can't run the test suite without getting this error.  I can't see where this role is being created. 

```
 Error: expected { errors: [ { message: 'role "does_not_exist" does not exist' } ] } response body, got { errors: [ { message: 'password authentication failed for user "postgraphql_tes
t_auth_role"' } ] }
      + expected - actual

       {
         "errors": [
￼
           {
      -      "message": "password authentication failed for user \"postgraphql_test_auth_role\""
      +      "message": "role \"does_not_exist\" does not exist"
           }
         ]
       }
```

The test suite is creating the other roles and schemas just not this role.  Not sure if this is a bug or if I'm doing something wrong. 

`npm run test`

![image](https://cloud.githubusercontent.com/assets/1326910/18803470/66c89c58-8244-11e6-9d28-0b28ebf1620a.png)

![image](https://cloud.githubusercontent.com/assets/1326910/18803476/6fa22682-8244-11e6-9891-4ab5577154a5.png)

**Comment by calebmer** [comment]
What version of Postgres are you using?

`postgraphql_test_auth_role` isn't a group role (as you're looking at above), but instead a user. See it's definition here: https://github.com/calebmer/postgraphql/blob/master/tests/createServer.test.js#L60

We expect that `postgraphql_test_auth_role` does *not* have a password (because we create it that way), your setup or Postgres version may be implicitly giving it a password, so the tests fail because we don't provide any password?

Try changing:

```sql
create user ${AUTH_ROLE};
```

To:

```sql
create user ${AUTH_ROLE} unencrypted password 'test';
```

Then add `pass: 'test'` here: https://github.com/calebmer/postgraphql/blob/master/tests/createServer.test.js#L20

(or maybe ``auth: `${AUTH_ROLE}:test` ``)

Then we'll be explicit about the user's password instead of implicitly assuming no password.

Resources:

- https://www.postgresql.org/docs/9.5/static/sql-createuser.html
- https://nodejs.org/api/url.html#url_url_format_urlobject

**Comment by calebmer** [comment]
Were you able to figure this out?

**Comment by tim-field** [comment]
Sorry, haven't had time yet. Will look at as soon as I can.
