### ISSUE TITLE
Any plans to support mysql 5.7?

### ISSUE THREAD

**Issue by sahin** [calebmer/postgraphql#19]
great lib @calebmer great work. do u have any plans to support mysql 5.7?

**Comment by calebmer** [comment]
I currently do not. I worked on a project earlier with the intention of having much wider support and it turned out the scope was a little to large.

That said, it would be fairly easy to port to MySQL considering we use a SQL builder that supports it and the schema detection is pretty pluggable. I'm not going to do it, but if someone wants to add support, I'll add them as a contributor 😊
