### ISSUE TITLE
Procedure Versioning

### ISSUE THREAD

**Issue by valorize** [calebmer/postgraphql#232]
I was thinking about how I structure my database and schemas the best and discovered the following article: http://tech.valgog.com/2012/01/schema-based-versioning-and-deployment.html

What do you think about the approach of saving procedures in different schemas for versioning logic?

**Comment by calebmer** [comment]
Ultimately, I think this best left up to you and your project.

From a PostGraphQL perspective (which inherits the GraphQL perspective), my initial recommendation is to never make a breaking change in the API. If you want a new function or a new implementation, find a new name. For example `register_person` -> `register_person_2`, or `register_person` -> `register_person_and_something_else`. If you want to delete the `register_person` implementation, it may then call the new function, but still preserve the same external callable API. So that’s my recommendation from a GraphQL perspective which recommends we avoid breaking change at all cost. Adding and deprecating instead of breaking.

That’s a very principled position to take and likely impractical, however (although Facebook does claim it has made less than 5 breaking changes in the entirety of their APIs existence :wink:). The only time where a refusal to make breaking changes may be practical is you have a native app that depends on an old API and you’re Facebook so not all 100% of your users have upgraded from their 3 year old app.

I don’t know how Postgres schemas play into this. [PostgREST](http://postgrest.com/) used schemas for a while to version. The first contribution I made to PostgREST was actually removing schema versioning support from the PostgREST internals though :wink: (https://github.com/begriffs/postgrest/issues/304, https://github.com/begriffs/postgrest/pull/308, https://github.com/begriffs/postgrest/pull/312, https://github.com/begriffs/postgrest/pull/314. there were a lot of PRs, it was my first large OSS contribution ok?). I don’t think versioning by schema is a bad idea at all, I just think it should be done at a project level and not a framework level.

As another note, PostGraphQL currently doesn’t handle naming collisions across schemas well. So if you had `v1.register_person` and `v2.register_person` and passed both the `v1` and `v2` schemas to PostGraphQL, it would throw an error. See https://github.com/calebmer/postgraphql/issues/191 for a discussion on how to handle these cases.

**Comment by calebmer** [comment]
Feel free to join the [Gitter community](https://gitter.im/calebmer/postgraphql) to talk about this and more :+1:

**Comment by valorize** [comment]
Thank you for your insights and the recommendations here and in https://github.com/calebmer/postgraphql/issues/235
