### ISSUE TITLE
Usage with "condition" parameter

### ISSUE THREAD

**Issue by motleydev** [calebmer/postgraphql#290]
Thanks to the reflection, we get access to first, last, offset, etc. I'm having a hard time understanding how to use the "condition" parameter. Is there a good example of this? Is it only for strict equality or can it be used for generic search like LIKE in postgres?

For example:

```
{
  person(condition: {
    name: '%Jo%'
  }) {
   name,
   age,
   ...
 }
}
```

**Comment by benjie** [comment]
See also #47

**Comment by calebmer** [comment]
`condition` only currently allows you to test equality 😖

See #47 for ongoing work to improve condition support. However, with procedures you can query however you would like without needing to wait for support in PostGraphQL. See the documentation on [advanced queries](https://github.com/calebmer/postgraphql/blob/master/docs/advanced-queries.md) and our [forum example tutorial](https://github.com/calebmer/postgraphql/blob/master/examples/forum/TUTORIAL.md#set-returning-functions). Such a procedure would look like this:

```sql
create function forum_example.search_posts(search text) returns setof forum_example.post as $$
  select post.*
  from forum_example.post as post
  where post.headline ilike ('%' || search || '%') or post.body ilike ('%' || search || '%')
$$ language sql stable;
```

I’m going to close this issue because #47 is more focused, but good question 👍

**Comment by machineghost** [comment]
This really should be re-opened, as it has nothing to do with #47.   This is a _documentation_ bug: nowhere in the documentation does it explain how to use condition arguments.

#47 is a functionality bug ... again, completely different.

**Comment by benjie** [comment]
Please use the “suggest improvements/edit this page” link at the top of this page to indicate how you believe the docs should be improved:

https://www.graphile.org/postgraphile/filtering/

**Comment by machineghost** [comment]
Sure, I just thought reopening an existing ticket made more sense than duplicating one.  Will duplicate!

**Comment by machineghost** [comment]
Crap, I need to fork the repo just to leave a comment?  I'll pass.

**Comment by benjie** [comment]
There’s two examples in the opening paragraph; it’s not clear what you’re asking for: do you want a full database schema, PostGraphile command line, and GraphQL query? Maybe just a full GraphQL query like this one? https://www.graphile.org/postgraphile/examples/#Collections__Relation_condition

You can suggest edits to the docs without leaving the GitHub web interface, but yes forking is part of that process since that’s necessary to raise a PR.

**Comment by machineghost** [comment]
Yes!  A simple link to https://www.graphile.org/postgraphile/examples/#Collections__Relation_condition on  that page would be marvelous.

And this is just my two cents, but if you make forking the repo part of the process, maybe that's not a good process, because it deters people from submitting feedback.

**Comment by benjie** [comment]
You can just file an issue against that repo if you want; but by allowing the PR route you can actually raise the change you want to see to the underlying text and be credited for your contribution. (Also I can then merge it from my phone, so it’ll be applied a lot sooner; I’ve not logged into my development machine for a week, am taking a little “holiday”.)

I wonder if you could explain why you feel forking a repo is such a big issue, to help me understand your concerns? Is it that you don’t want to raise the PR directly and would rather just raise an issue roughly describing the changes rather than figuring out the concrete changes yourself? If that’s it, would splitting the suggest link in two — one for concrete edits, and one for more vague suggestions — address your concerns?

**Comment by machineghost** [comment]
>I wonder if you could explain why you feel forking a repo is such a big issue, to help me understand your concerns? Is it that you don’t want to raise the PR directly and would rather just raise an issue roughly describing the changes rather than figuring out the concrete changes yourself? If that’s it, would splitting the suggest link in two — one for concrete edits, and one for more vague suggestions — address your concerns?

It's that it's more work to file a bug here than any other OSS project I've seen in my life.

Engineers are process people, and as a good engineer I'd think that you (like myself) would recoil at the idea of making a job harder than it needs to be (ie. harder than it it is anywhere else).

**Comment by benjie** [comment]
> It's that it's more work to file a bug here than any other OSS project I've seen in my life. 

> When it feels like someone is making a task needlessly difficult

> harder than it it is anywhere else

I hear your frustration, thank you for bringing this to my attention and I'm sorry I've failed so badly at this. I have put quite a bit of effort into making it easy to contribute, so I'm sure you can understand it's rather upsetting to hear that you feel that I've done such a bad job of it that there's no other open source project that makes it this hard; but I'm grateful that you would like to help us to resolve this.

Based on your feedback I've spent a little time looking at some of the open source projects that we use, to learn from them how to handle contributions to documentation pages. Here's my findings:

### TypeScript

e.g. https://www.typescriptlang.org/docs/handbook/utility-types.html

![Screenshot_20220105_203722](https://user-images.githubusercontent.com/129910/148285805-b57bcc88-4c4e-437a-9d75-328fcef97042.png)

Their link points at https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Utility%20Types.md ; it's then up to you to figure out how to file your feedback.

As you rightly say, I recoiled at the idea of making a job harder than it needs to be, so I went one step further than this - I did the equivalent of tracking down and clicking the subtle little edit button for the user, removing what I deemed to be an unnecessary step from the process.

### Node.js

e.g. https://nodejs.org/dist/latest-v16.x/docs/api/console.html

![Screenshot_20220105_204706](https://user-images.githubusercontent.com/129910/148287078-9dc85914-6590-411d-baac-cb5dafea22ef.png)

Node does the exact same flow as us - it takes you straight to having clicked that edit button (requiring a fork if you've not already forked the project):

https://github.com/nodejs/node/edit/master/doc/api/console.md

### Express.js

e.g. https://expressjs.com/en/api.html#req.app

![Screenshot_20220105_204849](https://user-images.githubusercontent.com/129910/148287281-2d1b2e90-1995-45b8-b7d9-4a6249e6af79.png)

Express uses a small link in the footer (which takes a while to scroll to since it's just one massive web page) which takes you to a directory index:

https://github.com/expressjs/expressjs.com/tree/gh-pages/_includes/api/en/4x

There doesn't appear to be a README or any other instructions, so it's then down to you to figure out which file you need to edit, and then figure out how to edit it.

I feel that we're two (quite significant) steps easier than this for raising a PR at least - we link you directly to the file to edit _and_ we click the edit button for you.

### PostgreSQL

e.g. https://www.postgresql.org/docs/current/sql-select.html

![Screenshot_20220105_204231](https://user-images.githubusercontent.com/129910/148286471-960c363b-cfa3-4581-abed-32bbe36c2a9e.png)

There's a link to a form at the bottom of the page to submit corrections. Upon clicking the link you need to create an account with PostgreSQL; you can do so with social login or username and password. If you use the handy Login with GitHub link then you get sent to an account management page, but if you then navigate back to the documentation page and click the form link a second time you're greeted with a form to fill out:

![Screenshot_20220105_235625](https://user-images.githubusercontent.com/129910/148306598-f2a20893-53f7-4c94-8004-0617e8fae71b.png)


The form requires your email address and makes it very clear that your post will be sent to a public mailing list, from your email address, which will be posted publicly on the internet permanently. The form isn't prepopulated with a subject or comment, so you may need to navigate back again to copy the content you want to suggest editing.

## Graphile

Our documentation gives you three ways to contribute: by clicking the "suggest" link at the top of a page you can either 1. raise a PR directly (with as minimal steps as I could accomplish), or 2. file an issue (by clicking the "issues" tab at the top of the GitHub page); alternatively there's option 3. which is to send us an email via the link at the bottom of every page of our site:

![Screenshot_20220105_204505](https://user-images.githubusercontent.com/129910/148286789-f4111688-4a88-47cf-9062-20fe64dc88b4.png)

Here's the flow for option 1; the flow for option 2 is similar but when you see the big "Fork this repository" button, you click the "Issues" tab:

![raising-a-pr](https://user-images.githubusercontent.com/129910/148306282-c56d9f11-17a5-4b1f-87bc-1110bf5aac0a.gif)

Compared to the other projects that use GitHub to manage their documentation it feels _to me_ that we are at least as good (and in some cases up to two steps better) when it comes to filing a PR, and equally good when it comes to filing an issue. Clearly you don't agree, but it's not clear to me how you think we should improve this process. I didn't spot any improvements available by studying the projects above; but it's very likely that I've missed something as I'm no expert on software documentation. **Some concrete suggestions of improvements would be appreciated**; I honestly don't know how to make it easier - please let me know! Thanks for working with me on this - together we can make it super easy for people to contribute :raised_hands:

**Comment by machineghost** [comment]
>I honestly don't know how to make it easier - please let me know! 

One simple suggestion: when a user asks for a tiny improvement to the documentation (literally one link), and you think it's reasonable ... just add it.

To be clear, I'm not saying to abandon good OSS project management practices; I'm saying when someone asks for a tiny improvement, which will take you 2 minutes to make but them 20 ... _at least_ don't be mad at them when then decline to do so.

**Comment by benjie** [comment]
I’m never mad at someone who doesn’t want to take the time to do open source work; it’s your time spend it as you will. I do actively want to remove barriers to contribution, though, so when someone brings a barrier to my attention (especially one that I wasn’t aware of) I like to take time to understand why it’s a barrier so that I can solve it.

At first it was absolutely not clear what kind of change you wanted which is why I suggested you make the edits yourself. It’s quite challenging, as I’m sure you can imagine, to see through the eyes of someone else - sometimes it takes a while to figure out what change would have addressed their concerns, which is why I typically provide resources and then let them make the change that they would have wanted to see. 

When you showed you did not like the process for doing this I wanted to understand the barrier; i.e. why is clicking the fork button such a barrier for you. I can’t improve things if I don’t understand why they’re wrong. As it is, I still do not understand why this is a barrier - I’d still appreciate you sharing why so that I can address these concerns.

I’ve made the edit as I would normally for someone who doesn’t want to raise a PR once it has become clear what change they need. It took me longer than usual because I was previously on holiday. I’m sorry if anything in the above makes you feel I was mad; I’m just trying to understand and to improve the project.
