### ISSUE TITLE
forum example: search by rowId not working

### ISSUE THREAD

**Issue by mrbarletta** [calebmer/postgraphql#30]
personNodes by id (base64 table+id) works 

This works:
```
{
  personNodes(id: "cGVyc29uOjI=") {
    nodes {
      id
      familyName
    }
  }
}
```

this does not:
```
{
  personNodes(rowId: 1) {
    nodes {
      id
      familyName
    }
  }
}
```

I've been checking the code and it looks it is trying to find a column name "rowId" which doesn't exist

**Comment by calebmer** [comment]
Thanks for reporting! This is fixed in `1.1.6`.

This is definitely an interesting way I didn't envision of selecting a single object by it's `rowId` 😊. I know @rattrayalex has expressed interest in writing a `personByRowId` field which would make this use case much easier.

There's also a [gitter chat room](https://gitter.im/calebmer/postgraphql) you can join if you want to talk about your experiences using PostGraphQL.
