### ISSUE TITLE
GraphQL Schema generation

### ISSUE THREAD

**Issue by sudheerj** [calebmer/postgraphql#313]
When we try to integrate GraphQL with PostgresQL then we found postgraphql as best option.After running the examples folder forum project then we ended up with few questions.How GraphQL schema will be generated? Where GraphQL Schema/queries will be stored? How we can integrate this postgraphQL in a complete front end -backend runnable application?

Note: We are successfully able to integrate with MongoDB and Cassandra DBs with GraphQL-JS implementation.

**Comment by kenota** [comment]
You should be able to get schema by using graphql introspection abilities.
That is how GraphiQl is able to do autocomplete and provide documentation
in right tab.

On 19 Jan 2017 04:46, "Dedoig" <notifications@github.com> wrote:

I actually had the same question. Is there a simple way to get the complete
GraphQL schema that was figured out by postgraphql as, say, a single file?

Am most impressed with postgraphql, wonderful work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/calebmer/postgraphql/issues/313#issuecomment-273681203>,
or mute the thread

**Comment by sudheerj** [comment]
Thanks Kenota for the response. Yeah it is based on graphql introspection abilities but I'am not sure where it stored GraphQL Schema(as a file etc) to get more control on the schema.

I'am looking for complex filter features enhancements as well.
https://github.com/calebmer/postgraphql/issues/47

**Comment by calebmer** [comment]
Check out the GraphQL-js [`introspectionQuery`](https://github.com/graphql/graphql-js/blob/5cf4cef688e115e08d9f53efba07bea174ec4446/src/utilities/introspectionQuery.js#L14-L106) to see the query that is recommended to get the schema PostGraphQL generates. I’d happily accept a PR that will automatically generate this schema in a JSON file for you on PostGraphQL startup, or whenever an update from the watch feature occurs 😊

@sudheerj make sure to check out the PostGraphQL [connection procedures](https://github.com/calebmer/postgraphql/blob/master/docs/procedures.md#connection-procedures). I think that’s just the thing you are looking for when it comes to complex filters 👍

**Comment by calebmer** [comment]
A feature for auto-exporting the schema was added in [`3.0.0`](https://github.com/calebmer/postgraphql/releases/tag/v3.0.0) thanks to @MaienM :tada:
