### ISSUE TITLE
Limit rows returned for specific users?

### ISSUE THREAD

**Issue by Kurren123** [calebmer/postgraphql#318]
Hi there

I have two database roles, Users and Admins. How can I limit the size of query results returned by graphQL by (e.g.) 100 rows for Users, but not limit the results for Admins?

Thank you for any suggestions,

Kurren

**Comment by benjie** [comment]
Hi @Kurren123, postgraphql doesn't implement any features like this in itself; but here's a couple of ways you might achieve it:

1. put some kind of GraphQL query validation service in front of postgraphql so that it can validate which queries area allowed and which are not before sending them on to postgraphql and postgres
2. add custom functions in Postgres that look at the current user's access levels and decide on the row limit accordingly
3. specify the row limit in a JWT token and use custom functions again

This may be of interest: https://github.com/calebmer/postgraphql/blob/master/docs/advanced-queries.md

**Comment by Kurren123** [comment]
Hi @benjie . Thank you for your reply. If I go with 2 or 3, how can I prevent a malicious client from selecting millions of rows?

**Comment by benjie** [comment]
One way is to not allow access to query the tables directly, instead requiring the user to go through your custom mutations. Another is to use built in postgres features such as statement timeout, to bolster your defence. 

However I'd strongly encourage you to go with option 1  though there's not any good ready-to-use solutions out there for this yet, as far as I know. I recommend this post on StackOverflow as a good starting point:

http://stackoverflow.com/a/37338465/141284

It sounds like your issue could be solved by writing a validation rule (like the  [built in ones here](https://github.com/graphql/graphql-js/tree/master/src/validation/rules)) that a) requires limits on certain endpoints, and b) ensures that those limits are sensible.

**Comment by Kurren123** [comment]
Thank you for your answer, much appreciated. I think we can close this issue 😄

**Comment by benjie** [comment]
@Kurren123 Do let us know if you build your own or find a solution, I think this area of GraphQL is still pretty cutting edge.
