### ISSUE TITLE
Aliasing undesirable field names

### ISSUE THREAD

**Issue by calebmer** [calebmer/postgraphql#34]
It seems like what a lot of people find undesirable about PostGraphQL is how fields are named. How can we build a system (whether it be a JSON map or otherwise) which allows people to rename automatically named fields?

Any ideas are welcome, I'm have no ideas at the moment.

**Comment by tobiasmuehl** [comment]
How about implementing the alias by reflection over the GraphQL schema?
Basically just copy everything but the name.
Since the schema and the types can easily be queried using`__schema` and `__types` it's easy and doesn't impact performance as the resolving functions are identical.
This feature could be included in the GraphQL-JS library seperate from PostGraphQL.

I'm unsure when this should happen. At Postgres reflection time, node.js server initalizing, sowhere in between?

**Comment by burkhardr** [comment]
Isn't [this](https://facebook.github.io/graphql/#sec-Field-Alias) what you're looking for?

**Comment by tobiasmuehl** [comment]
@burkhardr No, that's not what where are trying to achieve. We want to alias the Query-definitions, because the Relay-compliant schemas aren't that human friendly.
Example: Alias `users[0].posts[0].name` means `usersNodes[0].edges[0].node.postsNodesByUserId.edges[0].name`

**Comment by burkhardr** [comment]
Well, you could do that server-side, but the GraphQL connections / edges are named like that for a reason. The link I posted above allows you to do aliasing on the client-side, which - while not as convenient - is definitely the easier solution.

**Comment by tobiasmuehl** [comment]
This issue discusses a server side implementation. The thing with the alias in the query is that it's just working on one level.
With the built-in alias the only thing that actually happens is that the returned key has a different name, paths can't be simplified however. The primary function for alias is to be able to request and return multiple instances in one request.
By design this GraphQL query is impossible to fulfill
´´´
{ User(id: 1) {
  name,
  age
  },
  User(id: 2) {
  name,
  email
  }
}
´´´
Because it's impossible to return both objects on the same `me` key.

The aim of the discussed alias function is to make querying nicer, the builtin function just complicates the query as it's longer:
```
{ User1: User(id: 1) {
  name,
  age
  },
  User2: User(id: 2) {
  name,
  email
  }
}
```

**Comment by burkhardr** [comment]
If you think of GraphQL as a straight REST replacement, then data structures like `users[0].posts[0].name` make perfect sense. Unfortunately, we're dealing with a graph here, so you won't be able to simplify things like edges and nodes away without losing some of the functionality they provide (e.g. `pageInfo`).

If you're willing to sacrifice that for added simplicity, then this feature should be strictly opt-in.

**Comment by tobiasmuehl** [comment]
I don't understand why the feature should be opt-in.
The aliases have to be defined manually and they don't break the generated schema as they only offer a reference to the generated schema.

Can you elaborate?

**Comment by calebmer** [comment]
I finding a better name for fields like `postNodesByAuthorId` on the server is fine by me because I feel that's what a lot of people find issue with.

What do you think about using constraint names for these field names? So if the reference to `person` from the `author_id` column was named `author` our forward query name could be simply `author` and our reverse query name could be `postNodesByAuthor`.

Making connections optional is something I've discussed with @rattrayalex in #16. I don't really like the idea because it duplicates a lot of logic, but if enough people articulate a want/need I'll reconsider. I really think solving the `postNodesByAuthorId` naming solution is the best compromise.

**Comment by burkhardr** [comment]
Connections themselves shouldn't be optional. Inferring the name of the connection from the FK/column name makes sense to me, but you'll still not arrive at something like `users[0].posts[0].name` (you'll always have `edges[]`, `node`, etc. for connections).

Sorry for the confusion. My sole argument was around not being able to boil a graph down to the same format you'd get from a classical REST endpoint without sacrificing some of its functionality.

**Comment by calebmer** [comment]
Closing in favor of a discussion in #42.
