### ISSUE TITLE
Some example curl commands would be helpful

### ISSUE THREAD

**Issue by dbkaplun** [calebmer/postgraphql#78]
It would be nice if the README or [forum example](https://github.com/calebmer/postgraphql/tree/master/examples/forum) had some sample curl/wget commands to help one get started. As someone who is just experimenting with postgraphql and GraphQL in general, I would really appreciate it!

For instance, I am querying:
```graphql
{post {id}}
```

The error message `Field "post" argument "id" of type "ID!" is required but not provided.` is not so helpful!

**Comment by ferdinandsalis** [comment]
Instead of using wget or curl I suggest using graphiql, its the graphical interface for your graphql endpoint. If you start up PostGraphQL with the `--development` flag you can access it at the entry point of your grahlql server.

The error message is actually very descriptive. It just says that its missing the id argument. So to make your query work you need to add the id attribute to the query, which could look like this:
```graphql
{
  post(id: "YXJ0aXN0OjE=") { 
    id 
  }
}
```
This would get the post's id field belonging to the post. This is using the opaque id generated by PostGraphQL. If you want to use the id's of your database you will need to do the following:
```graphql
{
  postByRowId(rowId: 1) {
    id
  }
}
```
I hope this helped.

**Comment by dbkaplun** [comment]
Yes, I am familiar with the GraphiQL interface. I meant to add some curl commands specifically, because they are self-contained and serve as kind of canonical representations of HTTP requests. Any graphql query would do as the forum example has no sample queries. :/

Here is the solution I found to my problem:
```graphql
{
  postNodes {
    nodes {
    	id
    }
  }
}
```

**Comment by ferdinandsalis** [comment]
:) Glad you solved the problem.

**Comment by dbkaplun** [comment]
So are you planning on adding some sample queries to the forum example? Would be super helpful

**Comment by ferdinandsalis** [comment]
Adding sample queries to the forum example and explaining them would definitely help people new to GraphQL so I guess it would make sense. What do you think @calebmer?

**Comment by calebmer** [comment]
Yeah, adding sample queries is definetly something we should do.

**Comment by dbkaplun** [comment]
Made a PR with some sample queries: #85

**Comment by ferdinandsalis** [comment]
@dbkaplun thank you for the contribution!
